### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by neberding** [BryceStevenWilley/visioning_texts#9] opened 2020-01-20 23:43 UTC
I import my Whatsapp data from an email to myself from my phone to my computer then upload the file where you have the button and then click to see the results but everything comes up blank

**Comment by BryceStevenWilley** [comment] 2020-01-21 05:49
I need a little more info to help here.
* Is there anything in the console log (F12, console tab)?
* What's a typical line of the text file look like?

This also might be a duplicate of #2 and #5, which I just made some progress on. Let me know if I was able to fix it!

**Comment by BryceStevenWilley** [comment] 2020-04-30 02:15
Gonna close this, feel free to reopen with more info.

**Closed as completed by BryceStevenWilley** 2020-04-30 02:15 UTC
Labels: bug, confirm_fix
