### ISSUE TITLE
Not showing Whatsapp Data

### ISSUE THREAD

**Issue by biejay** [BryceStevenWilley/visioning_texts#5] opened 2020-01-20 18:55 UTC
Hey, thanks for your work!
Saw your example on Reddit which looked awesome. Unfortunately its **not working** when i upload a **.txt from whatsapp**.
Maybe due to 

1. **language format** (it's german and we got **Umlaute** :D) and

2.  **time format** (here it is dd/mm/YYYY)?

My format is actually the same like in 

> _Issue visualizing the data #3_

 but still my visualization looks worse.

Would be **awesome if you** could **update** this!

![Unbenannt](https://user-images.githubusercontent.com/8942784/72750769-07dd7380-3bbe-11ea-88d1-da033b603398.JPG)

**Comment by BryceStevenWilley** [comment] 2020-01-20 18:59
Thanks for the issue, I'll take a look into this this week. The first thing that would help a lot is if you could post the console log.  If you're in Chrome, should press F12 and go to the console tab.

**Comment by MilanFox** [comment] 2020-01-20 19:01
Can confirm the bug. Same language and time format.

Console outputs:

    Uncaught TypeError: Cannot read property 'concat' of undefined
    at math.js:32
    at Array.reduce (<anonymous>)
    at split_b_k_whatsapp (math.js:26)
    at FileReader.<anonymous> (graphs.js:481)

**Comment by biejay** [comment] 2020-01-20 19:25
Yes, got slightly the same output like @MilanFox :


    Uncaught TypeError: Cannot read property 'concat' of undefined
    at math.js:32
    at Array.reduce (<anonymous>)
    at split_b_k_whatsapp (math.js:26)
    at FileReader.<anonymous> (graphs.js:481)

**Comment by nmatni** [comment] 2020-01-20 23:44
I changed from dd/mm/YYY to mm/dd/YYYY and still have similar error
Uncaught TypeError: Cannot read property 'texts' of undefined
    at math.js:100
    at Array.reduce (<anonymous>)
    at xy_time_of_day (math.js:99)
    at graphs.js:485

**Comment by Vidhin05** [comment] 2020-01-21 01:24
I changed from dd/mm/YYY to mm/dd/YYYY and I'm getting 
```
Uncaught TypeError: Cannot read property 'texts' of undefined
    at math.js:101
    at Array.reduce (<anonymous>)
    at xy_time_of_day (math.js:100)
    at graphs.js:485
```

**Comment by BryceStevenWilley** [comment] 2020-01-21 05:39
@biejay, I'd try again, I made some progress on `dd/mm/yyyy` formats in #2, and I don't think that language differences will be an issue, as the strings being passed around already support emojis, so they're at least Unicode and not ASCII.

**Comment by BryceStevenWilley** [comment] 2020-01-22 03:47
@biejay, since you confirmed it's working for you in https://github.com/BryceStevenWilley/visioning_texts/issues/3#issuecomment-576606146, I'm going to close this issue. Everyone else, if you're still running into the issue, follow along at #2!

**Closed as completed by BryceStevenWilley** 2020-01-22 03:47 UTC
Labels: bug, duplicate
